const dotEnv = require("dotenv");

dotEnv.config();

module.exports = {
  PORT: process.env.PORT,
  DB_URL: process.env.MONGODB_URI,
  APP_SECRET: process.env.APP_SECRET,
  MESSAGE_BROKER_URL: process.env.MESSAGE_BROKER_URL,
  EXCHANGE_NAME: process.env.EXCHANGE_NAME,
  STACK_HOLDER_BINDING_KEY: process.env.STACK_HOLDER_BINDING_KEY,
  // PROJECT_BINDING_KEY: process.env.PROJECT_BINDING_KEY,
  // TASK_BINDING_KEY: process.env.TASK_BINDING_KEY,
  // PERMIT_BINDING_KEY: process.env.PERMIT_BINDING_KEY,
  // AUTHENTICATION_BINDING_KEY: process.env.AUTHENTICATION_BINDING_KEY,
  // NOTIFICATION_BINDING_KEY: process.env.NOTIFICATION_BINDING_KEY,
};