const navItems = [
    {
      href: '/',
      label: 'Dashboard',
      subMenu: [],
      icon: '/assets/svg/dashboard.svg',
      active: true,
    },
    {
      href: '/page',
      label: 'Pages',
      subMenu: [
        {
          href: '/starter',
          label: 'Starter',
          subMenu: [],
          icon: '/assets/svg/starter.svg',
          active: false,
        },
        {
          href: '/login',
          label: 'Login',
          subMenu: [],
          icon: '/assets/svg/login.svg',
          active: true,
        },
        {
          href: '/registration',
          label: 'Registration',
          subMenu: [],
          icon: '/assets/svg/registration.svg',
          active: false,
        },
        {
          href: '/forgot-password',
          label: 'Forgot Password',
          subMenu: [],
          icon: '/assets/svg/forget_question.svg',
          active: false,
        },
        {
          href: '/reset-password',
          label: 'Reset Password',
          subMenu: [],
          icon: '/assets/svg/reset.svg',
          active: false,
        },
        {
          href: '/locked-user',
          label: 'Locked User',
          subMenu: [],
          icon: '/assets/svg/locked_user.svg',
          active: false,
        },
        {
          href: '/code-verification',
          label: 'Code Verification',
          subMenu: [],
          icon: '/assets/svg/password.svg',
          active: false,
        },
        {
          href: '/check-your-email',
          label: 'Check Your Email',
          subMenu: [],
          icon: '/assets/svg/check_email.svg',
          active: false,
        },
        {
          href: '/time-line',
          label: 'Time Line',
          subMenu: [],
          icon: '/assets/svg/timeline.svg',
          active: false,
        },
        {
          href: '/pricing',
          label: 'Pricing',
          subMenu: [],
          icon: '/assets/svg/payment.svg',
          active: false,
        },
        {
          href: 'billing',
          label: 'Billing',
          subMenu: [],
          icon: '/assets/svg/receipt.svg',
          active: false,
        },
        {
          href: '/404',
          label: 'Error 404',
          subMenu: [],
          icon: '/assets/svg/warning.svg',
          active: false,
        },
        {
          href: '/500',
          label: 'Error 500',
          subMenu: [],
          icon: '/assets/svg/error.svg',
          active: false,
        },
        {
          href: '/faqs',
          label: 'FAQs',
          subMenu: [],
          icon: '/assets/svg/quiz.svg',
          active: false,
        },
        {
          href: '/gallery',
          label: 'Gallery',
          subMenu: [],
          icon: '/assets/svg/images-outline.svg',
          active: false,
        },
        {
          href: '/maintenance',
          label: 'Maintenance',
          subMenu: [],
          icon: '/assets/svg/engineering.svg',
          active: false,
        },
        {
          href: '/coming-soon',
          label: 'Coming Soon',
          subMenu: [],
          icon: '/assets/svg/footsteps-outline.svg',
          active: false,
        },
        {
          href: '/setting',
          label: 'Setting',
          subMenu: [],
          icon: '/assets/svg/setting.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/documents-outline.svg',
    },
    {
      href: '#',
      label: 'Applications',
      subMenu: [
        {
          href: '/Kanban',
          label: 'Kanban',
          subMenu: [],
          icon: '/assets/svg/kanban.svg',
          active: false,
        },
        {
          href: '/email-inbox',
          label: 'Email Inbox',
          subMenu: [],
          icon: '/assets/svg/email_inbox.svg',
          active: false,
        },
        {
          href: '/calendar',
          label: 'Calendar',
          subMenu: [],
          icon: '/assets/svg/calendar.svg',
          active: false,
        },
        {
          href: '/chat',
          label: 'Chat',
          subMenu: [],
          icon: '/assets/svg/chat_google.svg',
          active: false,
        },
        {
          href: '/projects',
          label: 'Projects',
          subMenu: [],
          icon: '/assets/svg/tactic.svg',
          active: false,
        },
        {
          href: '/invoice',
          label: 'Invoice',
          subMenu: [],
          icon: '/assets/svg/receipt-outline.svg',
          active: false,
        },
        {
          href: '/member-list',
          label: 'Member List',
          subMenu: [],
          icon: '/assets/svg/loyalty.svg',
          active: false,
        },
        {
          href: '/profile',
          label: 'Profile',
          subMenu: [],
          icon: '/assets/svg/profile.svg',
          active: false,
        },
        {
          href: '/form',
          label: 'Form',
          subMenu: [],
          icon: '/assets/svg/form.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/apps-outline.svg',
    },
    {
      href: '#',
      label: 'Inputs',
      subMenu: [
        {
          href: '/text-field',
          label: 'Text Field',
          subMenu: [],
          icon: '/assets/svg/text_fields.svg',
          active: false,
        },
        {
          href: '/text-area',
          label: 'Text Area',
          subMenu: [],
          icon: '/assets/svg/text_area.svg',
          active: false,
        },
        {
          href: '/select',
          label: 'Select',
          subMenu: [],
          icon: '/assets/svg/select.svg',
          active: false,
        },
        {
          href: '/multi-select',
          label: 'Multi-Select',
          subMenu: [],
          icon: '/assets/svg/multi-select.svg',
          active: false,
        },
        {
          href: '/checkbox',
          label: 'Checkbox',
          subMenu: [],
          icon: '/assets/svg/check_box.svg',
          active: false,
        },
        {
          href: '/radio',
          label: 'Radio',
          subMenu: [],
          icon: '/assets/svg/radio_button.svg',
          active: false,
        },
        {
          href: '/time-picker',
          label: 'Time Picker',
          subMenu: [],
          icon: '/assets/svg/time-outline.svg',
          active: false,
        },
        {
          href: '/date-picker',
          label: 'Date Picker',
          subMenu: [],
          icon: '/assets/svg/calendar-clear-outline.svg',
          active: false,
        },
        {
          href: '/date-range-picker',
          label: 'Date Range Picker',
          subMenu: [],
          icon: '/assets/svg/calendar-outline.svg',
          active: false,
        },
        {
          href: '/date-time-picker',
          label: 'Date-Time Picker',
          subMenu: [],
          icon: '/assets/svg/date_time.svg',
          active: false,
        },
        {
          href: '/slider',
          label: 'Slider',
          subMenu: [],
          icon: '/assets/svg/slider.svg',
          active: false,
        },
        {
          href: '/range',
          label: 'Range',
          subMenu: [],
          icon: '/assets/svg/range.svg',
          active: false,
        },
        {
          href: '/button',
          label: 'Button',
          subMenu: [],
          icon: '/assets/svg/touch.svg',
          active: false,
        },
        {
          href: '/rating',
          label: 'Rating',
          subMenu: [],
          icon: '/assets/svg/star-half-outline.svg',
          active: false,
        },
        {
          href: '/switch',
          label: 'Switch',
          subMenu: [],
          icon: '/assets/svg/toggle-outline.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/input.svg',
    },
    {
      href: '#',
      label: 'Data Display',
      subMenu: [
        {
          href: '/avatar',
          label: 'Avatar',
          subMenu: [],
          icon: '/assets/svg/avatar.svg',
          active: false,
        },
        {
          href: '/badges',
          label: 'Badges',
          subMenu: [],
          icon: '/assets/svg/badge.svg',
          active: false,
        },
        {
          href: '/chips',
          label: 'Chips',
          subMenu: [],
          icon: '/assets/svg/chip.svg',
          active: false,
        },
        {
          href: '/list',
          label: 'List',
          subMenu: [],
          icon: '/assets/svg/list.svg',
          active: false,
        },
        {
          href: '/tooltip',
          label: 'Tooltip',
          subMenu: [],
          icon: '/assets/svg/tooltip.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/tv-outline.svg',
    },
    {
      href: '#',
      label: 'Feedback',
      subMenu: [
        {
          href: '/alerts',
          label: 'Alerts',
          subMenu: [],
          icon: '/assets/svg/alert-circle-outline.svg',
          active: false,
        },
        {
          href: '/dialogs',
          label: 'Dialogs',
          subMenu: [],
          icon: '/assets/svg/dialogs.svg',
          active: false,
        },
        {
          href: '/progress',
          label: 'Progress',
          subMenu: [],
          icon: '/assets/svg/progress.svg',
          active: false,
        },
        {
          href: '/spinners',
          label: 'Spinners',
          subMenu: [],
          icon: '/assets/svg/spinner.svg',
          active: false,
        },
        {
          href: '/snack-bar',
          label: 'Snack-bar',
          subMenu: [],
          icon: '/assets/svg/text.svg',
          active: false,
        },
        {
          href: '/modals',
          label: 'Modals',
          subMenu: [],
          icon: '/assets/svg/modal.svg',
          active: false,
        },
        {
          href: '/offcanvas',
          label: 'Offcanvas',
          subMenu: [],
          icon: '/assets/svg/off-canvas.svg',
          active: false,
        },
        {
          href: '/toasters',
          label: 'Toasters',
          subMenu: [],
          icon: '/assets/svg/toast.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/feedback.svg',
    },
    {
      href: '#',
      label: 'Navigation',
      subMenu: [
        {
          href: '/breadcrumb',
          label: 'Breadcrumb',
          subMenu: [],
          icon: '/assets/svg/breadcrumb.svg',
          active: false,
        },
        {
          href: '/pagination',
          label: 'Pagination',
          subMenu: [],
          icon: '/assets/svg/last_page.svg',
          active: false,
        },
        {
          href: '/speed-dial',
          label: 'Speed Dial',
          subMenu: [],
          icon: '/assets/svg/add-circle-outline.svg',
          active: false,
        },
        {
          href: '/tabs',
          label: 'Tabs',
          subMenu: [],
          icon: '/assets/svg/toolbar.svg',
          active: false,
        },
        {
          href: '/carousel',
          label: 'Carousel',
          subMenu: [],
          icon: '/assets/svg/carousel.svg',
          active: false,
        },
        {
          href: '/navbar',
          label: 'Navbar',
          subMenu: [],
          icon: '/assets/svg/side_navigation.svg',
          active: false,
        },
        {
          href: '/nav',
          label: 'Nav',
          subMenu: [],
          icon: '/assets/svg/link-outline.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/golf-outline.svg',
    },
    {
      href: '#',
      label: 'Surfaces',
      subMenu: [
        {
          href: '/accordion',
          label: 'Accordion',
          subMenu: [],
          icon: '/assets/svg/list-outline.svg',
          active: false,
        },
        {
          href: '/card',
          label: 'Card',
          subMenu: [],
          icon: '/assets/svg/rectangle.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/easel-outline.svg',
    },
    {
      href: '#',
      label: 'Utils',
      subMenu: [
        {
          href: '/shadows',
          label: 'Shadows',
          subMenu: [],
          icon: '/assets/svg/shadow.svg',
          active: false,
        },
        {
          href: '/timeline',
          label: 'Timeline',
          subMenu: [],
          icon: '/assets/svg/timeline-outline.svg',
          active: false,
        },
        {
          href: '/tree-view',
          label: 'Tree view',
          subMenu: [],
          icon: '/assets/svg/tree.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/construct-outline.svg',
    },
    {
      href: '#',
      label: 'Table',
      subMenu: [
        {
          href: '/basic',
          label: 'Basic',
          subMenu: [],
          icon: '/assets/svg/simple-table.svg',
          active: false,
        },
        {
          href: '/sorting',
          label: 'Sorting',
          subMenu: [],
          icon: '/assets/svg/sort.svg',
          active: false,
        },
        {
          href: '/filtering',
          label: 'Filtering',
          subMenu: [],
          icon: '/assets/svg/filter-outline.svg',
          active: false,
        },
        {
          href: '/grouping',
          label: 'Grouping',
          subMenu: [],
          icon: '/assets/svg/group-table.svg',
          active: false,
        },
        {
          href: '/pagination',
          label: 'Pagination',
          subMenu: [],
          icon: '/assets/svg/last_page.svg',
          active: false,
        },
        {
          href: '/row-selection',
          label: 'Row Selection',
          subMenu: [],
          icon: '/assets/svg/table_rows.svg',
          active: false,
        },
        {
          href: '/expanding',
          label: 'Expanding',
          subMenu: [],
          icon: '/assets/svg/expand.svg',
          active: false,
        },
        {
          href: '/editable',
          label: 'Editable',
          subMenu: [],
          icon: '/assets/svg/edit.svg',
          active: false,
        },
        {
          href: '/drag-drop',
          label: 'Drag & Drop',
          subMenu: [],
          icon: '/assets/svg/expand-outline.svg',
          active: false,
        },
        {
          href: '/column-hiding',
          label: 'Column Hiding',
          subMenu: [],
          icon: '/assets/svg/eye-off-outline.svg',
          active: false,
        },
        {
          href: '/column-resizing',
          label: 'Column Resizing',
          subMenu: [],
          icon: '/assets/svg/resize.svg',
          active: false,
        },
        {
          href: '/sticky',
          label: 'Sticky',
          subMenu: [],
          icon: '/assets/svg/sticky_note.svg',
          active: false,
        },
        {
          href: '/umbrella',
          label: 'Umbrella',
          subMenu: [],
          icon: '/assets/svg/umbrella-outline.svg',
          active: false,
        },
        {
          href: '/empty',
          label: 'Empty',
          subMenu: [],
          icon: '/assets/svg/file-tray-outline.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/table-outline.svg',
    },
    {
      href: '#',
      label: 'Layout',
      subMenu: [
        {
          href: '/basic',
          label: 'Basic',
          subMenu: [],
          icon: '/assets/svg/basic-layout.svg',
          active: false,
        },
        {
          href: '/multi-column',
          label: 'Multi Column',
          subMenu: [],
          icon: '/assets/svg/column.svg',
          active: false,
        },
        {
          href: '/action-bar',
          label: 'Action Bar',
          subMenu: [],
          icon: '/assets/svg/action-layout.svg',
          active: false,
        },
        {
          href: '/stick-bar',
          label: 'Stick Bar',
          subMenu: [],
          icon: '/assets/svg/flex_direction.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/layout.svg',
    },
    {
      href: '#',
      label: 'Widgets',
      subMenu: [
        {
          href: '/statistics',
          label: 'Statistics',
          subMenu: [],
          icon: '/assets/svg/stats-chart-outline.svg',
          active: false,
        },
        {
          href: '/date',
          label: 'Date',
          subMenu: [],
          icon: '/assets/svg/today-outline.svg',
          active: false,
        },
        {
          href: '/chart',
          label: 'Chart',
          subMenu: [],
          icon: '/assets/svg/bar-chart-outline.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/widgets.svg',
    },
    {
      href: '#',
      label: 'Plugins',
      subMenu: [
        {
          href: '/clipboard',
          label: 'Clipboard',
          subMenu: [],
          icon: '/assets/svg/clipboard-outline.svg',
          active: false,
        },
        {
          href: '/editor',
          label: 'Editor',
          subMenu: [],
          icon: '/assets/svg/wysiwyg.svg',
          active: false,
        },
        {
          href: '/drop-zone',
          label: 'Drop-zone',
          subMenu: [],
          icon: '/assets/svg/pinch_zoom_out.svg',
          active: false,
        },
        {
          href: '/map',
          label: 'Map',
          subMenu: [],
          icon: '/assets/svg/map-outline.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/plugin.svg',
    },
    {
      href: '/icons',
      label: 'Icons',
      subMenu: [],
      icon: '/assets/svg/information-outline.svg',
    },
    {
      href: '#',
      label: 'Themes',
      subMenu: [
        {
          href: '/color',
          label: 'Color',
          subMenu: [],
          icon: '/assets/svg/color-palette-outline.svg',
          active: false,
        },
        {
          href: '/typography',
          label: 'Typography',
          subMenu: [],
          icon: '/assets/svg/match_case.svg',
          active: false,
        },
      ],
      icon: '/assets/svg/apps-outline.svg',
    },
];
  
export default navItems;